docker build  and push action

diff --git a/.github/workflows/docker-push.yaml b/.github/workflows/docker-push.yaml
--- a/.github/workflows/docker-push.yaml
+++ b/.github/workflows/docker-push.yaml
@@ -13,14 +13,28 @@ jobs:
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
 
     steps:
+      - name: Validate Secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "DOCKER_USERNAME missing"
+            exit 1
+          fi
+
+          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "DOCKER_PASSWORD missing"
+            exit 1
+          fi
+
+          echo "Secrets OK"
+
       - name: Checkout
         uses: actions/checkout@v4
-
-      - name: Login Docker Hub
-        uses: docker/login-action@v3
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+          ref: ${{ github.event.workflow_run.head_sha }}
+
+      - name: Docker Login (safe)
+        run: |
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
       - name: Build Image
         run: |
